######################################################################
# Automatically generated by qmake (3.0) Thu Sep 8 02:24:25 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = spinbox
INCLUDEPATH += .

# Input
SOURCES += spinbox.cpp
