######################################################################
# Automatically generated by qmake (3.0) Sun Dec 3 15:55:14 2017
######################################################################

TEMPLATE = app
TARGET = learnPage
INCLUDEPATH += .
QT += widgets

# Input
FORMS += learnPage.ui
SOURCES += main.cpp
