######################################################################
# Automatically generated by qmake (3.0) Wed Jul 8 15:32:20 2015
######################################################################

TEMPLATE = app
TARGET = hello3
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += window.hpp
SOURCES += window.cpp main.cpp
