######################################################################
# Automatically generated by qmake (3.0) Thu Sep 8 15:08:12 2016
######################################################################

TEMPLATE = app
TARGET = age2
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += widget.hpp
SOURCES += main.cpp widget.cpp
