# Generated by Django 2.1.5 on 2019-02-11 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('pol', 'Politics'), ('art', 'Art'), ('tech', 'Technology'), ('trivia', 'Trivial')], max_length=6)),
                ('region', models.CharField(choices=[('uk', 'UK News'), ('eu', 'European News'), ('w', 'World News')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=512)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Author')),
            ],
        ),
    ]
