######################################################################
# Automatically generated by qmake (3.0) Wed Oct 7 23:51:21 2015
######################################################################

TEMPLATE = app
TARGET = imgview
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += imgview.cpp
