######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 16:31:29 2015
######################################################################

TEMPLATE = app
TARGET = pixmap
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += pixmap.cpp
