######################################################################
# Automatically generated by qmake (3.0) Wed Jul 8 15:21:25 2015
######################################################################

TEMPLATE = app
TARGET = hello2
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += widget.hpp
SOURCES += widget.cpp main.cpp
