######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 21:34:19 2015
######################################################################

TEMPLATE = app
TARGET = button
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += button.cpp
