######################################################################
# Automatically generated by qmake (3.0) Sun Dec 3 16:03:08 2017
######################################################################

TEMPLATE = app
TARGET = homePage
INCLUDEPATH += .
QT += widgets

# Input
FORMS += homePage.ui
SOURCES += main.cpp
