/********************************************************************************
** Form generated from reading UI file 'homePage.ui'
**
** Created by: Qt User Interface Compiler version 5.3.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_HOMEPAGE_H
#define UI_HOMEPAGE_H

#include <QtCore/QDate>
#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDateTimeEdit>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Form
{
public:
    QPushButton *pushButton_3;
    QFrame *line;
    QLabel *label_2;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QLabel *label_3;
    QLineEdit *lineEdit;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QLabel *label_4;
    QLabel *label_5;
    QPushButton *pushButton_9;
    QPushButton *pushButton_11;
    QFrame *line_3;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QTableView *tableView;
    QLabel *label_6;
    QLabel *label_7;
    QSpinBox *spinBox;
    QSpinBox *spinBox_2;
    QLabel *label_8;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QFrame *line_2;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QFrame *line_13;
    QFrame *line_14;
    QFrame *line_15;
    QFrame *line_16;
    QFrame *line_17;
    QLabel *label_15;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_16;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_29;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QLabel *label_54;
    QLabel *label_56;
    QLabel *label_71;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_55;
    QLabel *label_50;
    QLabel *label_57;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QPushButton *pushButton_10;
    QLabel *label;
    QDateTimeEdit *dateTimeEdit_2;
    QLabel *label_9;

    void setupUi(QWidget *Form)
    {
        if (Form->objectName().isEmpty())
            Form->setObjectName(QStringLiteral("Form"));
        Form->resize(1132, 666);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(9);
        sizePolicy.setHeightForWidth(Form->sizePolicy().hasHeightForWidth());
        Form->setSizePolicy(sizePolicy);
        pushButton_3 = new QPushButton(Form);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(660, 90, 121, 41));
        pushButton_3->setStyleSheet(QLatin1String("color:rgb(255, 48, 29);\n"
"font: 75 Bold 22pt \"Cantarell\";"));
        pushButton_3->setCheckable(true);
        pushButton_3->setChecked(true);
        line = new QFrame(Form);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(20, 170, 1081, 20));
        line->setLineWidth(2);
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label_2 = new QLabel(Form);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(120, 610, 401, 20));
        label_2->setStyleSheet(QStringLiteral("font: 75 Bold 11pt \"Cantarell\";"));
        pushButton_4 = new QPushButton(Form);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(950, 90, 151, 41));
        pushButton_4->setStyleSheet(QLatin1String("color:rgb(23, 2, 255);\n"
"font: 75 Bold 22pt \"Cantarell\";"));
        pushButton_5 = new QPushButton(Form);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(800, 90, 131, 41));
        pushButton_5->setStyleSheet(QLatin1String("color:rgb(64, 109, 21);\n"
"font: 75 Bold 22pt \"Cantarell\";"));
        label_3 = new QLabel(Form);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(30, 580, 71, 71));
        label_3->setMaximumSize(QSize(141, 141));
        label_3->setSizeIncrement(QSize(0, 0));
        label_3->setBaseSize(QSize(12, 12));
        label_3->setPixmap(QPixmap(QString::fromUtf8("rsz_1touch.png")));
        lineEdit = new QLineEdit(Form);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(20, 140, 551, 31));
        pushButton = new QPushButton(Form);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(580, 140, 91, 31));
        pushButton->setStyleSheet(QStringLiteral("font: 75 Bold 11pt \"Cantarell\";"));
        pushButton_2 = new QPushButton(Form);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(680, 140, 131, 31));
        pushButton_2->setStyleSheet(QStringLiteral("font: 75 Bold 11pt \"Cantarell\";"));
        pushButton_6 = new QPushButton(Form);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(820, 140, 131, 31));
        pushButton_6->setStyleSheet(QStringLiteral("font: 75 Bold 11pt \"Cantarell\";"));
        pushButton_7 = new QPushButton(Form);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(960, 140, 81, 31));
        pushButton_7->setStyleSheet(QStringLiteral("font: 75 Bold 11pt \"Cantarell\";"));
        pushButton_8 = new QPushButton(Form);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(1050, 140, 51, 31));
        pushButton_8->setStyleSheet(QStringLiteral("font: 75 Bold 11pt \"Cantarell\";"));
        label_4 = new QLabel(Form);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(880, 40, 151, 41));
        label_4->setStyleSheet(QLatin1String("font: 75 Bold 25pt \"Cantarell\";\n"
"color:rgb(8, 8, 8);"));
        label_5 = new QLabel(Form);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(890, 10, 131, 31));
        label_5->setStyleSheet(QLatin1String("border-radius: 25px;\n"
"border-color: rgba(201, 76, 76, 0.3);\n"
"color:rgb(16, 16, 16);\n"
"font: 75 Bold 19pt \"Cantarell\";"));
        pushButton_9 = new QPushButton(Form);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(870, 590, 51, 51));
        QIcon icon;
        icon.addFile(QStringLiteral("facebook.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_9->setIcon(icon);
        pushButton_9->setIconSize(QSize(70, 70));
        pushButton_11 = new QPushButton(Form);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(930, 590, 51, 51));
        QIcon icon1;
        icon1.addFile(QStringLiteral("Twitter_bird_white_background.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_11->setIcon(icon1);
        pushButton_11->setIconSize(QSize(40, 40));
        line_3 = new QFrame(Form);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(20, 560, 1081, 20));
        line_3->setStyleSheet(QStringLiteral("font: Bold;"));
        line_3->setFrameShadow(QFrame::Sunken);
        line_3->setLineWidth(2);
        line_3->setMidLineWidth(0);
        line_3->setFrameShape(QFrame::HLine);
        pushButton_12 = new QPushButton(Form);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(990, 590, 51, 51));
        QIcon icon2;
        icon2.addFile(QStringLiteral("insta.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_12->setIcon(icon2);
        pushButton_12->setIconSize(QSize(40, 40));
        pushButton_13 = new QPushButton(Form);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(1050, 590, 51, 51));
        QIcon icon3;
        icon3.addFile(QStringLiteral("in.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_13->setIcon(icon3);
        pushButton_13->setIconSize(QSize(40, 40));
        tableView = new QTableView(Form);
        tableView->setObjectName(QStringLiteral("tableView"));
        tableView->setGeometry(QRect(690, 260, 411, 261));
        tableView->setAutoFillBackground(true);
        label_6 = new QLabel(Form);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 200, 421, 31));
        QFont font;
        font.setFamily(QStringLiteral("Cantarell"));
        font.setPointSize(22);
        font.setBold(true);
        font.setItalic(false);
        font.setWeight(75);
        label_6->setFont(font);
        label_6->setStyleSheet(QLatin1String("color:rgb(255, 48, 29);\n"
"font: 75 Bold 22pt \"Cantarell\";"));
        label_7 = new QLabel(Form);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(700, 210, 161, 31));
        label_7->setFont(font);
        label_7->setStyleSheet(QLatin1String("color:rgb(255, 48, 29);\n"
"font: 75 Bold 22pt \"Cantarell\";"));
        spinBox = new QSpinBox(Form);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setGeometry(QRect(910, 220, 51, 21));
        spinBox_2 = new QSpinBox(Form);
        spinBox_2->setObjectName(QStringLiteral("spinBox_2"));
        spinBox_2->setGeometry(QRect(1040, 220, 51, 22));
        spinBox_2->setMinimum(1);
        spinBox_2->setMaximum(2);
        label_8 = new QLabel(Form);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(860, 220, 41, 16));
        label_10 = new QLabel(Form);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(700, 330, 51, 16));
        label_11 = new QLabel(Form);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(700, 370, 61, 16));
        label_12 = new QLabel(Form);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(690, 410, 81, 16));
        label_13 = new QLabel(Form);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(690, 450, 61, 16));
        label_14 = new QLabel(Form);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(710, 490, 47, 13));
        line_2 = new QFrame(Form);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(690, 350, 411, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(Form);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(690, 390, 411, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(Form);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(690, 430, 411, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(Form);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(690, 470, 411, 16));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(Form);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(690, 310, 411, 16));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(Form);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(753, 260, 31, 261));
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(Form);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(780, 260, 51, 261));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(Form);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(810, 260, 61, 261));
        line_11->setFrameShape(QFrame::VLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(Form);
        line_12->setObjectName(QStringLiteral("line_12"));
        line_12->setGeometry(QRect(850, 260, 51, 261));
        line_12->setFrameShape(QFrame::VLine);
        line_12->setFrameShadow(QFrame::Sunken);
        line_13 = new QFrame(Form);
        line_13->setObjectName(QStringLiteral("line_13"));
        line_13->setGeometry(QRect(890, 260, 41, 261));
        line_13->setFrameShape(QFrame::VLine);
        line_13->setFrameShadow(QFrame::Sunken);
        line_14 = new QFrame(Form);
        line_14->setObjectName(QStringLiteral("line_14"));
        line_14->setGeometry(QRect(930, 260, 31, 261));
        line_14->setFrameShape(QFrame::VLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(Form);
        line_15->setObjectName(QStringLiteral("line_15"));
        line_15->setGeometry(QRect(970, 260, 21, 261));
        line_15->setFrameShape(QFrame::VLine);
        line_15->setFrameShadow(QFrame::Sunken);
        line_16 = new QFrame(Form);
        line_16->setObjectName(QStringLiteral("line_16"));
        line_16->setGeometry(QRect(1010, 260, 21, 261));
        line_16->setFrameShape(QFrame::VLine);
        line_16->setFrameShadow(QFrame::Sunken);
        line_17 = new QFrame(Form);
        line_17->setObjectName(QStringLiteral("line_17"));
        line_17->setGeometry(QRect(1020, 260, 81, 261));
        line_17->setFrameShape(QFrame::VLine);
        line_17->setFrameShadow(QFrame::Sunken);
        label_15 = new QLabel(Form);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(770, 280, 21, 16));
        QFont font1;
        font1.setPointSize(7);
        label_15->setFont(font1);
        label_17 = new QLabel(Form);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(850, 280, 21, 16));
        label_17->setFont(font1);
        label_18 = new QLabel(Form);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(950, 280, 21, 16));
        label_18->setFont(font1);
        label_19 = new QLabel(Form);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(880, 280, 21, 16));
        label_19->setFont(font1);
        label_20 = new QLabel(Form);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(920, 280, 21, 16));
        label_20->setFont(font1);
        label_21 = new QLabel(Form);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(990, 280, 21, 16));
        label_21->setFont(font1);
        label_23 = new QLabel(Form);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(1030, 280, 21, 16));
        label_23->setFont(font1);
        label_24 = new QLabel(Form);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(1070, 280, 21, 16));
        label_24->setFont(font1);
        label_25 = new QLabel(Form);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(810, 280, 21, 16));
        label_25->setFont(font1);
        label_16 = new QLabel(Form);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(810, 330, 47, 16));
        QFont font2;
        font2.setPointSize(6);
        label_16->setFont(font2);
        label_26 = new QLabel(Form);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(850, 330, 47, 16));
        label_26->setFont(font2);
        label_27 = new QLabel(Form);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(880, 330, 31, 20));
        label_27->setFont(font2);
        label_28 = new QLabel(Form);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(990, 330, 47, 16));
        label_28->setFont(font2);
        label_30 = new QLabel(Form);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(1030, 330, 47, 16));
        label_30->setFont(font2);
        label_31 = new QLabel(Form);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(920, 330, 31, 20));
        label_31->setFont(font2);
        label_29 = new QLabel(Form);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(810, 370, 47, 16));
        label_29->setFont(font2);
        label_32 = new QLabel(Form);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(850, 370, 47, 16));
        label_32->setFont(font2);
        label_33 = new QLabel(Form);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(950, 370, 31, 20));
        label_33->setFont(font2);
        label_34 = new QLabel(Form);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(920, 370, 31, 20));
        label_34->setFont(font2);
        label_35 = new QLabel(Form);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(1030, 370, 47, 16));
        label_35->setFont(font2);
        label_36 = new QLabel(Form);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(1070, 370, 47, 16));
        label_36->setFont(font2);
        label_37 = new QLabel(Form);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(810, 410, 47, 16));
        label_37->setFont(font2);
        label_38 = new QLabel(Form);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(770, 450, 47, 16));
        label_38->setFont(font2);
        label_39 = new QLabel(Form);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(810, 450, 31, 20));
        label_39->setFont(font2);
        label_40 = new QLabel(Form);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(850, 450, 31, 20));
        label_40->setFont(font2);
        label_41 = new QLabel(Form);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(880, 450, 47, 16));
        label_41->setFont(font2);
        label_42 = new QLabel(Form);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(1030, 450, 47, 16));
        label_42->setFont(font2);
        label_43 = new QLabel(Form);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(880, 490, 47, 16));
        label_43->setFont(font2);
        scrollArea = new QScrollArea(Form);
        scrollArea->setObjectName(QStringLiteral("scrollArea"));
        scrollArea->setGeometry(QRect(10, 250, 631, 291));
        scrollArea->setAutoFillBackground(false);
        scrollArea->setFrameShadow(QFrame::Sunken);
        scrollArea->setWidgetResizable(false);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QStringLiteral("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, -210, 609, 499));
        label_54 = new QLabel(scrollAreaWidgetContents);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(50, 80, 16, 20));
        label_56 = new QLabel(scrollAreaWidgetContents);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(50, 140, 16, 20));
        label_71 = new QLabel(scrollAreaWidgetContents);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(50, 360, 16, 20));
        label_44 = new QLabel(scrollAreaWidgetContents);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(20, 50, 131, 16));
        QFont font3;
        font3.setFamily(QStringLiteral("Cantarell"));
        font3.setPointSize(11);
        font3.setBold(true);
        font3.setItalic(false);
        font3.setWeight(75);
        label_44->setFont(font3);
        label_44->setStyleSheet(QStringLiteral("font: 75 Bold 11pt \"Cantarell\";"));
        label_45 = new QLabel(scrollAreaWidgetContents);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(70, 90, 531, 16));
        label_46 = new QLabel(scrollAreaWidgetContents);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(70, 110, 531, 16));
        label_46->setStyleSheet(QStringLiteral("font: 75  11pt \"Cantarell\";"));
        label_47 = new QLabel(scrollAreaWidgetContents);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(70, 150, 531, 16));
        label_48 = new QLabel(scrollAreaWidgetContents);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(70, 170, 531, 16));
        label_49 = new QLabel(scrollAreaWidgetContents);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(20, 230, 131, 16));
        label_49->setFont(font3);
        label_49->setStyleSheet(QStringLiteral("font: 75 Bold 11pt \"Cantarell\";"));
        label_55 = new QLabel(scrollAreaWidgetContents);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(50, 260, 16, 20));
        label_50 = new QLabel(scrollAreaWidgetContents);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(70, 270, 531, 16));
        label_57 = new QLabel(scrollAreaWidgetContents);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(50, 300, 16, 20));
        label_51 = new QLabel(scrollAreaWidgetContents);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(70, 310, 531, 16));
        label_52 = new QLabel(scrollAreaWidgetContents);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(70, 330, 531, 16));
        label_53 = new QLabel(scrollAreaWidgetContents);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(70, 370, 531, 16));
        label_58 = new QLabel(scrollAreaWidgetContents);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(20, 430, 131, 16));
        label_58->setFont(font3);
        label_58->setStyleSheet(QStringLiteral("font: 75 Bold 11pt \"Cantarell\";"));
        label_59 = new QLabel(scrollAreaWidgetContents);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(60, 460, 16, 20));
        label_60 = new QLabel(scrollAreaWidgetContents);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(80, 470, 531, 16));
        scrollArea->setWidget(scrollAreaWidgetContents);
        pushButton_10 = new QPushButton(Form);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(1030, 10, 71, 71));
        pushButton_10->setStyleSheet(QLatin1String("background-color: white;\n"
"color:rgb(255, 48, 29);\n"
"font: 75 Bold 19pt \"Cantarell\";"));
        QIcon icon4;
        icon4.addFile(QStringLiteral("../learnPage/close.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_10->setIcon(icon4);
        pushButton_10->setIconSize(QSize(60, 60));
        label = new QLabel(Form);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 10, 541, 81));
        label->setStyleSheet(QStringLiteral("color:rgb(64, 109, 21);"));
        label->setPixmap(QPixmap(QString::fromUtf8("../learnPage/minervaheader_qas.svg")));
        dateTimeEdit_2 = new QDateTimeEdit(Form);
        dateTimeEdit_2->setObjectName(QStringLiteral("dateTimeEdit_2"));
        dateTimeEdit_2->setEnabled(true);
        dateTimeEdit_2->setGeometry(QRect(20, 100, 361, 32));
        dateTimeEdit_2->setFocusPolicy(Qt::WheelFocus);
        dateTimeEdit_2->setAcceptDrops(true);
        dateTimeEdit_2->setWrapping(false);
        dateTimeEdit_2->setFrame(true);
        dateTimeEdit_2->setReadOnly(false);
        dateTimeEdit_2->setButtonSymbols(QAbstractSpinBox::NoButtons);
        dateTimeEdit_2->setAccelerated(false);
        dateTimeEdit_2->setKeyboardTracking(false);
        dateTimeEdit_2->setDateTime(QDateTime(QDate(2017, 12, 5), QTime(14, 15, 0)));
        dateTimeEdit_2->setDate(QDate(2017, 12, 5));
        dateTimeEdit_2->setTime(QTime(14, 15, 0));
        dateTimeEdit_2->setMaximumTime(QTime(23, 59, 59));
        dateTimeEdit_2->setCalendarPopup(true);
        dateTimeEdit_2->setTimeSpec(Qt::OffsetFromUTC);
        label_9 = new QLabel(Form);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(990, 220, 41, 16));
        tableView->raise();
        pushButton_3->raise();
        line->raise();
        label_2->raise();
        pushButton_4->raise();
        pushButton_5->raise();
        label_3->raise();
        lineEdit->raise();
        pushButton->raise();
        pushButton_2->raise();
        pushButton_6->raise();
        pushButton_7->raise();
        pushButton_8->raise();
        label_4->raise();
        label_5->raise();
        pushButton_9->raise();
        pushButton_11->raise();
        line_3->raise();
        pushButton_12->raise();
        pushButton_13->raise();
        label_6->raise();
        label_7->raise();
        spinBox->raise();
        spinBox_2->raise();
        label_8->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        label_13->raise();
        label_14->raise();
        line_2->raise();
        line_4->raise();
        line_5->raise();
        line_6->raise();
        line_7->raise();
        line_8->raise();
        line_10->raise();
        line_11->raise();
        line_12->raise();
        line_13->raise();
        line_14->raise();
        line_15->raise();
        line_16->raise();
        line_17->raise();
        label_15->raise();
        label_17->raise();
        label_18->raise();
        label_19->raise();
        label_20->raise();
        label_21->raise();
        label_23->raise();
        label_24->raise();
        label_25->raise();
        label_16->raise();
        label_26->raise();
        label_27->raise();
        label_28->raise();
        label_30->raise();
        label_31->raise();
        label_29->raise();
        label_32->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        label_38->raise();
        label_39->raise();
        label_40->raise();
        label_41->raise();
        label_42->raise();
        label_43->raise();
        scrollArea->raise();
        pushButton_10->raise();
        label->raise();
        dateTimeEdit_2->raise();
        label_9->raise();

        retranslateUi(Form);

        QMetaObject::connectSlotsByName(Form);
    } // setupUi

    void retranslateUi(QWidget *Form)
    {
        Form->setWindowTitle(QApplication::translate("Form", "Form", 0));
        pushButton_3->setText(QApplication::translate("Form", "HOME", 0));
        label_2->setText(QApplication::translate("Form", "Copyright \302\251 Taranvir Bola, Liam Peel, Kieron Hushon", 0));
        pushButton_4->setText(QApplication::translate("Form", "DISCOVER", 0));
        pushButton_5->setText(QApplication::translate("Form", "LEARN", 0));
        label_3->setText(QString());
        lineEdit->setText(QString());
        lineEdit->setPlaceholderText(QApplication::translate("Form", "Search", 0));
        pushButton->setText(QApplication::translate("Form", "Library", 0));
        pushButton_2->setText(QApplication::translate("Form", "Student Services", 0));
        pushButton_6->setText(QApplication::translate("Form", "Printer Credits", 0));
        pushButton_7->setText(QApplication::translate("Form", "OneDrive", 0));
        pushButton_8->setText(QApplication::translate("Form", "eMail", 0));
        label_4->setText(QApplication::translate("Form", "LOG OUT", 0));
        label_5->setText(QApplication::translate("Form", "Joe Bloggs", 0));
        pushButton_9->setText(QString());
        pushButton_11->setText(QString());
        pushButton_12->setText(QString());
        pushButton_13->setText(QString());
        label_6->setText(QApplication::translate("Form", "Announcements", 0));
        label_7->setText(QApplication::translate("Form", "Timetable", 0));
        label_8->setText(QApplication::translate("Form", "Week ", 0));
        label_10->setText(QApplication::translate("Form", "Monday", 0));
        label_11->setText(QApplication::translate("Form", "Tuesday", 0));
        label_12->setText(QApplication::translate("Form", "Wednesday", 0));
        label_13->setText(QApplication::translate("Form", "Thursday", 0));
        label_14->setText(QApplication::translate("Form", "Friday", 0));
        label_15->setText(QApplication::translate("Form", "9-10", 0));
        label_17->setText(QApplication::translate("Form", "11-12", 0));
        label_18->setText(QApplication::translate("Form", "2-3", 0));
        label_19->setText(QApplication::translate("Form", "12-1", 0));
        label_20->setText(QApplication::translate("Form", "1-2", 0));
        label_21->setText(QApplication::translate("Form", "3-4", 0));
        label_23->setText(QApplication::translate("Form", "4-5", 0));
        label_24->setText(QApplication::translate("Form", "5-6", 0));
        label_25->setText(QApplication::translate("Form", "10-11", 0));
        label_16->setText(QApplication::translate("Form", "2711", 0));
        label_26->setText(QApplication::translate("Form", "2931", 0));
        label_27->setText(QApplication::translate("Form", "lab", 0));
        label_28->setText(QApplication::translate("Form", "2421", 0));
        label_30->setText(QApplication::translate("Form", "2211", 0));
        label_31->setText(QApplication::translate("Form", "lab", 0));
        label_29->setText(QApplication::translate("Form", "2421", 0));
        label_32->setText(QApplication::translate("Form", "2811", 0));
        label_33->setText(QApplication::translate("Form", "lab", 0));
        label_34->setText(QApplication::translate("Form", "lab", 0));
        label_35->setText(QApplication::translate("Form", "2711", 0));
        label_36->setText(QApplication::translate("Form", "2921", 0));
        label_37->setText(QApplication::translate("Form", "2921", 0));
        label_38->setText(QApplication::translate("Form", "2421", 0));
        label_39->setText(QApplication::translate("Form", "lab", 0));
        label_40->setText(QApplication::translate("Form", "lab", 0));
        label_41->setText(QApplication::translate("Form", "2711", 0));
        label_42->setText(QApplication::translate("Form", "2211", 0));
        label_43->setText(QApplication::translate("Form", "2931", 0));
        label_54->setText(QApplication::translate("Form", "1", 0));
        label_56->setText(QApplication::translate("Form", "2", 0));
        label_71->setText(QApplication::translate("Form", "3", 0));
        label_44->setText(QApplication::translate("Form", "COMP2711", 0));
        label_45->setText(QApplication::translate("Form", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", 0));
        label_46->setText(QApplication::translate("Form", "ut labore et dolore magna aliqua.", 0));
        label_47->setText(QApplication::translate("Form", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", 0));
        label_48->setText(QApplication::translate("Form", "ut labore et dolore magna aliqua.", 0));
        label_49->setText(QApplication::translate("Form", "COMP2211", 0));
        label_55->setText(QApplication::translate("Form", "1", 0));
        label_50->setText(QApplication::translate("Form", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", 0));
        label_57->setText(QApplication::translate("Form", "2", 0));
        label_51->setText(QApplication::translate("Form", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", 0));
        label_52->setText(QApplication::translate("Form", "ut labore et dolore magna aliqua.", 0));
        label_53->setText(QApplication::translate("Form", "Lorem ipsum dolor sit amet.", 0));
        label_58->setText(QApplication::translate("Form", "COMP2931", 0));
        label_59->setText(QApplication::translate("Form", "1", 0));
        label_60->setText(QApplication::translate("Form", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", 0));
        pushButton_10->setText(QString());
        label->setText(QString());
        dateTimeEdit_2->setSpecialValueText(QString());
        dateTimeEdit_2->setDisplayFormat(QApplication::translate("Form", "dd/MM/yyyy HH:mm", 0));
        label_9->setText(QApplication::translate("Form", "Sem", 0));
    } // retranslateUi

};

namespace Ui {
    class Form: public Ui_Form {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HOMEPAGE_H
