######################################################################
# Automatically generated by qmake (3.0) Fri Dec 1 16:28:44 2017
######################################################################

TEMPLATE = app
TARGET = PRACTICE
INCLUDEPATH += .
QT += widgets

# Input
FORMS += learnPage.ui
SOURCES += main.cpp
