######################################################################
# Automatically generated by qmake (3.0) Fri Dec 1 17:05:29 2017
######################################################################

TEMPLATE = app
TARGET = volume
INCLUDEPATH += .

# Input
HEADERS += window.hpp
FORMS += volume.ui
SOURCES += main.cpp window.cpp
