######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 16:30:22 2015
######################################################################

TEMPLATE = app
TARGET = number
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += number.cpp
