######################################################################
# Automatically generated by qmake (3.0) Sun Dec 3 16:00:18 2017
######################################################################

TEMPLATE = app
TARGET = discoverPage
INCLUDEPATH += .
QT += widgets

# Input
FORMS += discoverPage.ui
SOURCES += main.cpp
