######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 16:09:23 2015
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += hello.cpp
