######################################################################
# Automatically generated by qmake (3.0) Thu Oct 8 16:29:00 2015
######################################################################

TEMPLATE = app
TARGET = form
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += form.cpp
