######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 16:33:00 2015
######################################################################

TEMPLATE = app
TARGET = gif
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += gif.cpp
