######################################################################
# Automatically generated by qmake (3.0) Thu Oct 8 16:49:11 2015
######################################################################

TEMPLATE = app
TARGET = grid
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += grid.cpp
