######################################################################
# Automatically generated by qmake (3.0) Tue Nov 28 16:20:23 2017
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .
QT+= widgets

# Input
SOURCES += hello.cpp
