######################################################################
# Automatically generated by qmake (3.0) Wed Oct 7 23:54:05 2015
######################################################################

TEMPLATE = app
TARGET = tabs
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += tabs.cpp
