######################################################################
# Automatically generated by qmake (3.0) Tue Oct 13 15:27:45 2015
######################################################################

TEMPLATE = app
TARGET = control
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += controller.hpp
SOURCES += controller.cpp main.cpp
