######################################################################
# Automatically generated by qmake (3.0) Thu Sep 8 15:08:12 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = age
INCLUDEPATH += .

# Input
HEADERS += widget.hpp
SOURCES += main.cpp widget.cpp
