######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 21:39:02 2015
######################################################################

TEMPLATE = app
TARGET = combo
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += combo.cpp
