######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 16:25:54 2015
######################################################################

TEMPLATE = app
TARGET = label
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += label.cpp
