######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 21:36:48 2015
######################################################################

TEMPLATE = app
TARGET = checkbox
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += checkbox.cpp
