######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 21:52:26 2015
######################################################################

TEMPLATE = app
TARGET = textfield
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += textfield.cpp
