######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 21:51:10 2015
######################################################################

TEMPLATE = app
TARGET = slider
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += slider.cpp
