######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 21:45:18 2015
######################################################################

TEMPLATE = app
TARGET = postcode
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += postcode.hpp
SOURCES += main.cpp postcode.cpp
