######################################################################
# Automatically generated by qmake (3.0) Wed Oct 7 23:52:23 2015
######################################################################

TEMPLATE = app
TARGET = msgbox
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += msgbox.cpp
