int changeDirectory(char **args);
int info();
int programExit();
int directoryList();
int currentDirectory();
int programExecute(char **args);
int backgroundExecute(char **args);
int pipelining(char **args);
int shell();
int directing(char **args);
