######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 16:34:39 2015
######################################################################

TEMPLATE = app
TARGET = browser
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += browser.cpp
