#!/bin/bash

export CLASSPATH=.:../lib/junit-4.12.jar:../lib/hamcrest-all-1.3.jar

echo "Compiling..."
echo

javac -d . ../src/Card.java || exit 3
javac -d . ../src/CardCollection.java || exit 3
javac -d . ../src/PokerException.java || exit 3
javac -d . ../src/Deck.java || exit 3
javac -d . ../src/PokerHand.java || exit 3

javac -d . FullTests.java || exit 2

java org.junit.runner.JUnitCore FullTests
